version: '3.6'

services:

  mysql:
    image: mysql:8.0
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: app
      MYSQL_PASSWORD: itsasecret
      MYSQL_DATABASE: app
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 5s
      retries: 3

  phpfpm:
    build: .
    volumes:
      - ./app:/app
      - ./php.ini:/opt/bitnami/php/etc/conf.d/php.ini
    depends_on:
      mysql:
        condition: service_healthy

  nginx:
    image: bitnami/nginx:1.19
    ports:
      - 8080:80
    volumes:
      - ./app:/app
      - ./server.conf:/opt/bitnami/nginx/conf/server_blocks/server.conf
    depends_on:
      - phpfpm
